---
version: '3'
services:

  web:
    build:
      context: .
      dockerfile: ./packages/manager/Dockerfile
      target: manager
    container_name: web
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000']
      interval: 15s
      timeout: 10s
      retries: 10

  e2e:
    build:
      context: .
      dockerfile: ./packages/manager/Dockerfile
      target: e2e
    user: "${UID}:${GID}"
    depends_on:
      web:
        condition: service_healthy
    environment:
      - CYPRESS_BASE_URL=http://web:3000
    env_file: ./packages/manager/.env
    volumes:
      - .:/app
